version: '3.8'

services:
  backend:
    environment:
      - RAILS_ENV=development
    stdin_open: true
    tty: true

  frontend:
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true