AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "db/migrate/*"
    - "vendor/**/*"
    - "bin/*"
    - "config/boot.rb"
    - "config/environment.rb"
    - "config/application.rb"
    - "config/environments/*"
    - "config/initializers/*"
    - "config.ru"
    - "Rakefile"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "app/controllers/api/v1/admin_controller.rb"

Metrics/AbcSize:
  Exclude:
    - "app/controllers/api/v1/admin_controller.rb"

Metrics/ClassLength:
  Max: 100
  Exclude:
    - "app/controllers/api/v1/attendances_controller.rb"
    - "app/controllers/api/v1/admin_controller.rb"
    - "app/models/attendance.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Naming/VariableNumber:
  Enabled: false

Lint/ShadowedException:
  Enabled: false
